version: '3'
services:
  api:                                  # 后端springboot容器
    image: zhangtao25/sean-api:main
    container_name: sean-api    # 容器名为'xiao-xiao-su-api'
    restart: always                     # 重启策略: 容器退出时总是重启容器
    ports:                              # 映射端口
      - "24000:8080"
    volumes:
      - ./conf/application.yml:/app/conf/application.yml
  web:                                  # 前端node容器(运行nginx中的Vue项目)
    image: zhangtao25/sean:main
    container_name: sean    # 容器名为'xiao-xiao-su-web'
    restart: always                     # 重启策略: 容器退出时总是重启容器
    ports:
      - "25000:8080"                      # 映射端口
    depends_on:                          # 依赖于api容器，被依赖容器启动后此web容器才可启动
      - api
