datasource:
  mongodb:
    type: mongodb
    host: 127.0.0.1
    port: 27017
    username: root
    password: root
    database: evaporator
    requestSchemaName: request
    fileSchemaName: file
    workspaceSchemaName: workspace
    userSchemaName: user

gitlab:
  application:
    clientId: clientId
    clientSecret: clientSecret
    redirectUri: redirectUri
    uri: uri
